IMAGE_NAME = ENV["IMAGE_NAME"] || "bento/ubuntu-18.04"
WORKER_NODES = ENV["WORKER_NODES"] || 2
BASE_IP = ENV["BASE_IP"] || "10.0.0"
KUBERNETES_VERSION= ENV["KUBERNETES_VERSION"] || "1.20.6-00"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "gitlab-runner" do |gitlab-runner|
      master.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
      end
      master.vm.box = IMAGE_NAME
      master.vm.network "private_network", ip: "#{BASE_IP}.#{20}"
      master.vm.hostname = "gitlab-runner"
      master.vm.provision "ansible" do |ansible|
          ansible.playbook = "gitlab-runner-setup/gitlab-runner-playbook.yaml"
          ansible.verbose = true
          ansible.extra_vars = {
            node_ip: "#{BASE_IP}.#{10}",
            kubernetes_version: KUBERNETES_VERSION,
          }
      end
  end
end